services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: 'rick'
      POSTGRES_PASSWORD: 'rick'
      POSTGRES_DB: 'user-service'
    ports:
      - '5432:5432'
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:
networks:
  backend:
